version: '3'
services:
  etl-stream:
    image: avidito/kafka-stream-py:2.0.2-puska-etl-1.0
    build:
      context: ./services/etl-stream
    environment:
      - DWH_DB_HOSTNAME=${DWH_DB_HOSTNAME:-db-dwh}
      - DWH_DB_PORT=${DWH_DB_PORT:-5432}
      - DWH_DB_NAME=${DWH_DB_NAME:-puska}
      - DWH_DB_USER=${DWH_DB_USER:-puska}
      - DWH_DB_PASSWORD=${DWH_DB_PASSWORD:-puska}
    entrypoint: ["sleep", "infinity"]
    volumes:
      - ./services/etl-stream/etl:/scripts/etl