version: '3'
services:
  etl-stream:
    build:
      context: ./stream
    environment:
      - DWH_DB_HOSTNAME=${DWH_DB_HOSTNAME:-localhost}
      - DWH_DB_PORT=${DWH_DB_PORT:-5601}
      - DWH_DB_NAME=${DWH_DB_NAME:-puska}
      - DWH_DB_USER=${DWH_DB_USER:-puska}
      - DWH_DB_PASSWORD=${DWH_DB_PASSWORD:-puska}
    entrypoint: ["sleep", "infinity"]
    volumes:
      - ./stream:/scripts