x-puska-etl-common:
  &puska-etl-common
  environment:
    &puska-etl-common-env
    DWH_USERNAME: ${DWH_USER:-puska}
    DWH_PASSWORD: ${DWH_PASSWORD:-puska}
    DWH_HOSTNAME: ${DWH_HOSTNAME:-db-dwh}
    DWH_PORT: ${DWH_PORT:-5432}
    DWH_NAME: ${DWH_NAME:-puska}
    KAFKA_HOST: ${KAFKA_HOST:-kafka}
    KAFKA_PORT: ${KAFKA_PORT:-9092}
    WEBSOCKET_HOST: ${WEBSOCKET_HOST:-websocket}
    WEBSOCKET_PORT: ${WEBSOCKET_PORT:-8765}
    BI_TERNAK_TOPIC: ${BI_TERNAK_TOPIC:-bi-ternak}
services:
  distribusi:
    build:
      context: .
    network_mode: "host"
    environment:
      <<: *puska-etl-common-env
      KAFKA_TOPIC: ${KAFKA_TOPIC:-distribusi}
    entrypoint: ["python", "-m", "etl.seq_fact_distribusi.run"]

  populasi:
    build:
      context: .
    network_mode: "host"
    environment:
      <<: *puska-etl-common-env
      KAFKA_TOPIC: ${KAFKA_TOPIC:-populasi}
    entrypoint: ["python", "-m", "etl.seq_fact_populasi.run"]

  produksi:
    build:
      context: .
    network_mode: "host"
    environment:
      <<: *puska-etl-common-env
      KAFKA_TOPIC: ${KAFKA_TOPIC:-produksi}
    entrypoint: ["python", "-m", "etl.seq_fact_produksi.run"]